# Keep only the SSH/lab management interface eno12399 managed by NetworkManager.
# The remaining physical NICs are configured manually by the latency scripts.
[keyfile]
unmanaged-devices=interface-name:eno12409;interface-name:eno12419;interface-name:eno12429;interface-name:enp10s0np0;interface-name:ens5f0np0;interface-name:ens5f1np1;interface-name:ens6f0np0;interface-name:ens6f1np1;interface-name:ens7f0np0;interface-name:ens7f1np1
